version: '3.8'

services:
  server-ftp:
    container_name: server-ftp
    build:
      context: ./
      dockerfile: ./server.Dockerfile
    mac_address: $SERVER_MAC
    environment:
      - FTP_USER=$FTP_USER
      - FTP_PASSWORD=$FTP_PASSWORD
    networks:
      ftpnet:
        ipv4_address: $SERVER_IP
    volumes:
      - ./ftp-server:/data #server path
  attacker-ftp:
    container_name: attacker
    build:
      context: ./
      dockerfile: ./attacker.Dockerfile
      args:
        - IP-src=$SERVER_IP
        - MAC-src=$SERVER_MAC
        - IP-target=$CLIENT_IP
        - MAC-target=$CLIENT_MAC
    networks:
      ftpnet:
        ipv4_address: $ATTACKER_IP
    mac_address: $ATTACKER_MAC
    depends_on:
      - server-ftp
  client-ftp:
    container_name: client-ftp
    build:
      context: ./
      dockerfile: ./client.Dockerfile
    mac_address: $CLIENT_MAC
    networks:
      ftpnet:
        ipv4_address: $CLIENT_IP
    volumes:
      - ./ftp-client:/data #client path
    depends_on:
      - attacker-ftp

networks:
  ftpnet:
    ipam:
      driver: default
      config:
        - subnet: $SUBNET_RANGE