version: '3.8'

services:
  server-ftp:
    container_name: server-ftp
    build:
      context: ./
      dockerfile: ./server.Dockerfile
    mac_address: $SERVER_MAC
    environment:
      - CUSTOM_USER=user
      - PASSWORD=$FTP_PASSWORDD
    networks:
      - ftpnet
    volumes:
      - ./ftp-server:/data #server path
  attacker-ftp:
    container_name: attacker
    build:
      context: ./
      dockerfile: ./attacker.Dockerfile
    mac_address: $ATTACKER_MAC
  client-ftp:
    container_name: client-ftp
    build:
      context: ./
      dockerfile: ./client.Dockerfile
    mac_address: $CLIENT_MAC
    networks:
      ftpnet:
        ipv4_address: $CLIENT_IP
    volumes:
      - ./ftp-client:/data #client path

networks:
  ftpnet:
    ipam:
      driver: default
      config:
        - subnet: $SUBNET_RANGE
