version: '3.8'

services:
  server-ftp:
    container_name: server-ftp
    build:
      context: ./
      dockerfile: ./server.Dockerfile
    mac_address: $SERVER_MAC
    environment:
      - FTP_USER=$FTP_USER
      - FTP_PASSWORD=$FTP_PASSWORD
    networks:
      ftpnet:
        ipv4_address: $SERVER_IP
    volumes:
      - ./ftp-server:/home/abc #Server path
  attacker-ftp:
    container_name: attacker
    build:
      context: ./
      dockerfile: ./attacker.Dockerfile
    environment:
      - IP_SRC=$SERVER_IP
      - MAC_SRC=$SERVER_MAC
      - IP_TARGET=$CLIENT_IP
      - MAC_TARGET=$CLIENT_MAC
    networks:
      ftpnet:
        ipv4_address: $ATTACKER_IP
    mac_address: $ATTACKER_MAC
    depends_on:
      - server-ftp
      - client-ftp
  client-ftp:
    container_name: client-ftp
    build:
      context: ./
      dockerfile: ./client.Dockerfile
    mac_address: $CLIENT_MAC
    ports:
      - 3000:3000 # FTP client web
    networks:
      ftpnet:
        ipv4_address: $CLIENT_IP
    volumes:
      - ./ftp-client:/data #client path
    depends_on:
      - server-ftp

networks:
  ftpnet:
    ipam:
      driver: default
      config:
        - subnet: $SUBNET_RANGE